In [6]:
from nba_api.stats.endpoints import leaguegamefinder
from nba_api.stats.library.parameters import Season
from nba_api.stats.library.parameters import SeasonType

gamefinder = leaguegamefinder.LeagueGameFinder(
                            season_nullable=Season.default,
                            season_type_nullable=SeasonType.regular)

In [21]:
games_dict = gamefinder.get_normalized_dict()
games = games_dict['LeagueGameFinderResults']
all_games = []
for game in games:
    all_games.append([game["GAME_ID"],game["TEAM_NAME"],game["MATCHUP"],game["GAME_DATE"]])

all_games[-1]

['0022200002', 'Golden State Warriors', 'GSW vs. LAL', '2022-10-18']

In [22]:
# from nba_api.stats.endpoints import playbyplay
# df = playbyplay.PlayByPlay("0022200002").get_data_frames()[0]
# df.to_csv("first_game_of_22_23_nba_season.csv")

In [25]:
import pandas as pd
df = pd.read_csv("first_game_of_22_23_nba_season.csv",index_col=0)
df

,GAME_ID,EVENTNUM,EVENTMSGTYPE,EVENTMSGACTIONTYPE,PERIOD,WCTIMESTRING,PCTIMESTRING,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,SCORE,SCOREMARGIN
0,22200002,2,12,0,1,10:41 PM,12:00,NaN,Start of 1st Period (10:41 PM EST),NaN,NaN,NaN
1,22200002,4,10,0,1,10:41 PM,12:00,Jump Ball Looney vs. Davis: Tip to James,NaN,NaN,NaN,NaN
2,22200002,7,6,1,1,10:41 PM,11:43,Looney P.FOUL (P1.T1) (T.Brothers),NaN,NaN,NaN,NaN
3,22200002,9,1,6,1,10:41 PM,11:37,NaN,NaN,Davis 3' Driving Layup (2 PTS),2 - 0,-2
4,22200002,10,2,78,1,10:42 PM,11:21,MISS Wiggins 9' Floating Jump Shot,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
521,22200002,784,3,12,4,1:13 AM,0:45,NaN,NaN,Pippen Jr. Free Throw 2 of 2 (2 PTS),106 - 123,17
522,22200002,785,2,1,4,1:13 AM,0:34,MISS Kuminga 3PT Jump Shot,NaN,NaN,NaN,NaN
523,22200002,786,4,0,4,1:13 AM,0:30,NaN,NaN,Christie REBOUND (Off:0 Def:1),NaN,NaN
524,22200002,787,1,1,4,1:13 AM,0:22,NaN,NaN,Christie 25' 3PT Jump Shot (3 PTS) (Swider 1 AST),109 - 123,14
525,22200002,789,13,0,4,1:14 AM,0:00,NaN,End of 4th Period (1:14 AM EST),NaN,109 - 123,14